- name: print mongodb
  ansible.builtin.debug:
    msg: mongodb

- name: copy mangodb config file
  ansible.builtin.copy:
    src: mangodb.repo
    dest: /etc/yum.repos.d/

- name: Install mongoDB
  ansible.builtin.yum:
    name: mongodb-org
    state: installed



