- name: print mongodb
  ansible.builtin.debug:
    msg: mongodb

- name: copy mangodb config file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/

- name: Install mongoDB
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: update listzen IP address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start mongoDB services
  ansible.builtin.systemd:
     name: mongod
     state: restarted
     enabled: yes

- name: download and extract the files
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/mongodb/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Load the schemas js files
  community.mongodb.mongodb_shell:
    file: '/tmp/mongodb-main/catalogue.js'
    idempotent: yes

- name: Load the schemas js files
  community.mongodb.mongodb_shell:
    file: '/tmp/mongodb-main/user.js'
    idempotent: yes



