- name: play variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: URL= {{URL}}

- name: play variables from file
  hosts: all
  vars_files:
   - sample-vars.yml
  tasks:
   - name: print variable from file
     ansible.builtin.debug:
       msg: URL = {{URL}}

- name: task level variables
  hosts: all
  tasks:
    - name : task level veriables
      ansibl.builtin.debug:
        msg: URL = {{URL}}
      vars:
         URL: task.example.com